spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.254.134:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.254.133
    port: 6379
    password:


wechat:
  mpAppId: wx6c72b00c0d427c3c
  mpAppSecret: a41731ce1e0127f45f2dfbecacd02949
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projecturl:
  wechatMpAuthorize: http://localhost:8080
  wechatOpenAuthorize: http://localhost:8080
  sell: http://localhost:8080
# 打印SQL日志
logging:
  level:
    com.etoak.sell.dataobject.mapper: trace
# 加载mapper.xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  servlet:
    context-path: /sell
